[package]
name = "rss"
version = "0.1.0"
edition = "2021"

[dependencies]
league-client = { path = "../league-client" }
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
